config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :rotums do
    resources :travels do

    end
  end

  resources :vehicles do

  end

  resources :days do
  end

  resources :users do

  end

  resources :travels do
    resources :patients do

    end
  end

  devise_scope :user do
    post "sign_up", to: "registrations#create"
    get "new_sign_up", to: "registrations#new"
    #delete "user_delete", to: "registrations#destroy"
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :rotum
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :travel
end

app/models/rotum.rb
class Rotum < ApplicationRecord
  has_many :rotums
  has_many :days
  has_many :rotum_vehicles
  has_many :vehicles, through: :rotum_vehicles
  has_many :travels

  validates :origem, presence: true
  validates :destino, presence: true
  validates :hr_partida, presence: true
end

app/models/rotum_vehicle.rb
class RotumVehicle < ApplicationRecord
  belongs_to :rotum
  belongs_to :vehicle
end

app/models/travel.rb
class Travel < ApplicationRecord
  belongs_to :rotum
  has_many :travel_vehicles
  has_many :vehicles, through: :travel_vehicles
  has_many :patients
end

app/models/travel_vehicle.rb
class TravelVehicle < ApplicationRecord
  belongs_to :travel
  belongs_to :vehicle
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :address
  validates :email, presence: true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_many :rotum_vehicles
  has_many :rotums, through: :rotum_vehicles
  has_many :travel_vehicles
  has_many :travel, through: :travel_vehicles
  validates :modelo, presence: true
  validates :ano, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :authenticate_user!, only: [ :home ]
  def home
    @users = User.all
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  #before_action :set_patient, only: [:show, :edit, :update, :destroy]

  def create
    @travel = Travel.find(params[:travel_id])
    @patient = Patient.new(patient_params)
    @patient.travel = @travel
    if @patient.save!
      redirect_to travel_path(@travel) ,notice: "Criado com sucesso"
    else
      render :show
    end
  end

  def destroy
    @travel = Travel.find(params[:travel_id])
    @patient = Patient.find(params[:id])
    if @patient.destroy
      redirect_to travel_path(@travel)
    else
      render :show
    end

  end

  private

  def patient_params
    params.require(:patient).permit(:name, :cel, :cpf, :city, :acompanhantes, :destino, :travel_id)
  end

#  def set_patient
#    @patient = Patient.find(params[:id])
#    raise
#  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  respond_to :json
  def new
    @users = User.all
  end

  def create
    @user = User.create(sign_up_params)
    if @user.save
      render json: {
        messages: "Register In Successfully",
        is_success: true,
        data: {user: @user}
      }
    else
      render :status => 400,
             :json => {:message => @user.errors.full_messages}
    end
  end


  private

  def sign_up_params
    params.permit(:email, :username, :password, :role)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/rotums_controller.rb
class RotumsController < ApplicationController
  before_action :set_rotum, only: [:show, :edit, :update, :destroy]
  def index
    @rotums = Rotum.all
  end

  def show
    @rotum_run = @rotum.travels.where.not(status:"Finalizado")
    @rotum_history = @rotum.travels.where(status:"Finalizado")
    @travel = Travel.new
  end

  def new
    @rotum = Rotum.new
    @rotums = Rotum.last
  end

  def create
    @rotum = Rotum.new(rotum_params)
    if @rotum.save!
      redirect_to rotum_path(@rotum), notice: "Criado com sucesso"
    else
      render :new
    end
  end

  private

  def rotum_params
    params.require(:rotum).permit(:origem, :destino, :capacidade, :especialidade, :hr_partida)
  end

  def set_rotum
    @rotum = Rotum.find(params[:id])
  end

end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :set_travel, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
  end

  def show
    @patients = @travel.patients
    @patient = Patient.new
  end

  def create
    @travel = Travel.new(travel_params)
    @rotum = Rotum.find(params[:rotum_id])
    @travel.rotum = @rotum
    @travel.status = params[:travel][:status]
    @vehicle = Vehicle.find(params[:travel][:vehicle])
    if @travel.save!
      #redirect_to travel_path(@travel)
      TravelVehicle.create(travel:@travel, vehicle:@vehicle)
      flash[:alert] = "Viagem Criada com sucesso"
      redirect_to rotum_path(@rotum)
    else
      flash[:alert] = "Erro"
    end
  end

  private

  def travel_params
    params.permit(:status, :rotum_id, :vehicle)
  end

  def set_travel
    @travel = Travel.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def edit
  end

  def update
    raise
  end

  def destroy
    if @user.destroy
      redirect_to root_path
    else
      render root_path
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]
  def index
    @vehicles = Vehicle.all
  end

  def show
    raise
  end

  def new
    @vehicle = Vehicle.new
    @vehicles = Vehicle.all
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    if @vehicle.save
      redirect_to new_vehicle_path, notice: "Criado com sucesso"
    else
      render :new
    end
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  def update
    if @vehicle.update(vehicle_params)
      redirect_to root_path, notice: "Vehicle was sucessfully updated."
    else
      render :edit
    end
  end

  def destroy
    @vehicle.destroy
    redirect_to new_vehicle_path, notice: "Veículo deletado com sucesso"
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:montadora, :modelo, :ano, :placa, :capacidade, :status)
  end

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tfd</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
<style>
body {
  background-color: white;
}

.tablevehicle{

}

.app-container {
  display: flex;
  min-height: 0 !important;
  flex-direction: column;
  margin: 0;
}


img{
	width: 100%;
}
.login {
    height: 1000px;
    width: 100%;
    background: radial-gradient(#76f9f9, #43bbc891);
    position: relative;
}
.login_box {
    width: 1050px;
    height: 600px;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%,-50%);
    background: #fff;
    border-radius: 10px;
    box-shadow: 1px 4px 22px -8px #0004;
    display: flex;
    overflow: hidden;
}
.login_box .left{
  width: 41%;
  height: 100%;
  padding: 25px 25px;

}
.login_box .right{
  width: 59%;
  height: 100%
}
.left .top_link a {
    color: #452A5A;
    font-weight: 400;
}
.left .top_link{
  height: 20px
}
.left .contact{
	display: flex;
    align-items: center;
    justify-content: center;
    align-self: center;
    height: 100%;
    width: 73%;
    margin: auto;
}
.left h3{
  text-align: center;
  margin-bottom: 40px;
}
.left input {
    border: none;
    width: 80%;
    margin: 15px 0px;
    border-bottom: 1px solid #ec225e;
    padding: 7px 9px;
    width: 100%;
    overflow: hidden;
    background: transparent;
    font-weight: 600;
    font-size: 14px;
}
.left{
	background: white;
}
.submit {
    border: none;
    padding: 15px 70px;
    border-radius: 8px;
    display: block;
    margin: auto;
    margin-top: 120px;
    background: #ec225e;
    color: #fff;
    font-weight: bold;
    -webkit-box-shadow: 0px 9px 15px -11px rgba(88,54,114,1);
    -moz-box-shadow: 0px 9px 15px -11px rgba(88,54,114,1);
    box-shadow: 0px 9px 15px -11px rgba(88,54,114,1);
}


#submit {
    border: none;
    padding: 15px 70px;
    border-radius: 8px;
    display: block;
    margin: auto;
    margin-top: 120px;
    background: #ec225e;
    color: #fff;
    font-weight: bold;
    -webkit-box-shadow: 0px 9px 15px -11px rgba(88,54,114,1);
    -moz-box-shadow: 0px 9px 15px -11px rgba(88,54,114,1);
    box-shadow: 0px 9px 15px -11px rgba(88,54,114,1);
}


.right {
	background: linear-gradient(212.38deg, rgba(57, 95, 242, 0.7) 0%, rgba(21, 202, 232, 0.71) 100%),url(https://static.seattletimes.com/wp-content/uploads/2019/01/web-typing-ergonomics-1020x680.jpg);
	color: #fff;
	position: relative;
}

.right .right-text{
  height: 100%;
  position: relative;
  transform: translate(0%, 45%);
}
.right-text h2{
  display: block;
  width: 100%;
  text-align: center;
  font-size: 50px;
  font-weight: 500;
}
.right-text h5{
  display: block;
  width: 100%;
  text-align: center;
  font-size: 19px;
  font-weight: 400;
}

.right .right-inductor{
  position: absolute;
  width: 70px;
  height: 7px;
  background: #fff0;
  left: 50%;
  bottom: 70px;
  transform: translate(-50%, 0%);
}
.top_link img {
    width: 28px;
    padding-right: 7px;
    margin-top: -3px;
}



/* Card List Rotum */

.card-product {
  overflow: hidden;
  height: 160px;
  background: white;
  box-shadow: 0 0 15px rgba(0,0,0,0.2);
  display: flex;
  align-items: center;
}

.card-product img {
  height: 100%;
  width: 120px;
  object-fit: cover;
}

.card-product h2 {
  font-size: 16px;
  font-weight: bold;
  margin: 0;
}

.card-product p {
  font-size: 12px;
  line-height: 1.4;
  opacity: .7;
  margin-bottom: 0;
  margin-top: 8px;
}

.card-product .card-product-infos {
  padding: 16px;
}

.app-header__logo .logo-src {
  height: 23px;
  width: 97px;
  background: url(assets/images);
}



</style>
 <body>
  <div class="offcanvas offcanvas-start text-bg-dark" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasExampleLabel">Offcanvas</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div>
      Some text as placeholder. In real life you can have the elements you have chosen. Like, text, images, lists, etc.
    </div>
    <div class="dropdown mt-3">
      <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown">
        Dropdown button
      </button>
      <ul class="dropdown-menu">
        <li><a class="dropdown-item" href="#">Action</a></li>
        <li><a class="dropdown-item" href="#">Another action</a></li>
        <li><a class="dropdown-item" href="#">Something else here</a></li>
      </ul>
    </div>
  </div>
</div>
  <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render "shared/navbar2" %>
<%= render "shared/flashes" %>
<div class="container mt-3">
  <div class="card shadow border-primary" style="--bs-border-opacity: .2;">
    <div class="card-body callout callout-primary">
      <h5 class="card-title mt-3"><h2>Olá, Boa tarde</h2></h5>
      <p class="card-text mt-5">
        <%= link_to "Cadastrar Veículo", new_vehicle_path, class:"btn btn-success" %>
        <%= link_to "Criar usuário", new_sign_up_path, class:"btn btn-success" %>
        <%= link_to "Criar Rota", new_rotum_path, class:"btn btn-success" %>
        <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
      </p>
    </div>
  </div>
  <!-- Card Dashboard 1 -->
  <div class="row">
    <!-- Initial Row -->
    <div class="col-md-6 col-xl-4 mt-4">
      <div class="card mb-3 widget-content bg-midnight-bloom">
        <div class="widget-content-wrapper text-white">
          <div class="widget-content-left">
            <div class="widget-heading">Veículos</div>
            <div class="widget-subheading">Veículos Cadastrados</div>
          </div>
          <div class="widget-content-right">
            <div class="widget-numbers text-white"><span><%= Vehicle.all.count %></span></div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-6 col-xl-4 mt-4">
      <div class="card mb-3 widget-content bg-arielle-smile">
        <div class="widget-content-wrapper text-white">
          <div class="widget-content-left">
            <div class="widget-heading">Veículos</div>
            <div class="widget-subheading">Disponíveis</div>
          </div>
          <div class="widget-content-right">
            <div class="widget-numbers text-white"><span><%= Vehicle.where(status:"Liberado").count %></span></div>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-6 col-xl-4 mt-4">
      <div class="card mb-3 widget-content bg-grow-early">
        <div class="widget-content-wrapper text-white">
          <div class="widget-content-left">
            <div class="widget-heading">Veículos</div>
            <div class="widget-subheading">Em Manutencão</div>
          </div>
          <div class="widget-content-right">
            <div class="widget-numbers text-white"><span><%= Vehicle.where(status:"Em Manutencão").count %></span></div>
          </div>
        </div>
      </div>
    </div>

  </div>
  <!-- Finaly Row -->
  <!-- Init First Table -->
  <div class="row">
    <div class="col-md-12">
      <div class="main-card mb-3 card">
        <div class="card-header">Usuários Ativos
          <div class="btn-actions-pane-right">
          </div>
        </div>
        <div class="table-responsive">
          <table
            class="align-middle mb-0 table table-borderless table-striped table-hover">
            <thead>
              <tr>
                <th class="text-center">#</th>
                <th>Email</th>
                <th class="text-center">Cargo</th>
              </tr>
            </thead>
            <tbody>
             <% @users.each do |u| %>
              <tr>
                <td class="text-center text-muted"><%= u.id %></td>
                <td>
                  <div class="widget-content p-0">
                    <div class="widget-content-wrapper">
                      <div class="widget-content-left mr-3">
                        <div class="widget-content-left">
                          <img width="40" class="rounded-circle"  alt="">
                        </div>
                      </div>
                      <div class="widget-content-left flex2">
                        <div class="widget-heading"><%= u.email %></div>
                        <div class="widget-subheading opacity-7"></div>
                      </div>
                    </div>
                  </div>
                </td>
                <% if u.role == true %>
                <% @cargo = "Admin" %>
                <% else %>
                <% @cargo = "Motorista" %>
                <% end %>
                <td class="text-center">
                  <div class="badge badge-warning"><%= @cargo %></div>
                </td>
                <td class="text-center">
                  <button class="mr-2 btn-icon btn-icon-only btn btn-outline-danger">
                  <%= link_to "", user_path(u), data: { turbo_method: :delete, turbo_confirm: "Tem certeza?" }, class: "pe-7s-trash btn-icon-wrapper" %></button>
                  </button>
          <button class="btn-wide btn btn-success">Edit</button>
                </td>
              </tr>
              <% end %>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="d-block text-center card-footer">
        </div>
      </div>
    </div>
  </div>
  <!-- Finaly First Table -->

app/views/rotums/index.html.erb
<%= render "shared/navbar2" %>
<div class="container mt-5">
  <% @rotums.each do |r| %>
  <div class="card-product mt-5">
    <img
      src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg"/>
    <div class="card-product-infos mt-2 mb-2">
      <p>Origem:</p>
      <h2><%= r.origem %></h2>
      <p>Destino:</p>
      <h2><%= r.destino %></h2>
      <p><strong>Especialidade: </strong><%= r.especialidade %></p>
      <%= link_to "Visualizar", rotum_path(r), class: "btn btn-info btn-sm m-2" %>
    </div>
  </div>
  <% end %>
</div>

app/views/rotums/new.html.erb
<%= render "shared/navbar2" %>
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="d-flex justify-content-center bg-white rounded p-5 shadow">
      <%= form_with model: @rotum, url: { action: "create" }, class:"row g-1 w-10", local: false do |form| %>
        <%= form.label :origem %>
        <%= form.text_field :origem, class:"form-control form-control-sm col-auto" %>
        <div><%= form.label :destino %></div>
        <%= form.text_field :destino, class:"form-control form-control-sm col-auto" %>
        <div><%= form.label :especialidade %></div>
        <%= form.text_field :especialidade, class:"form-control form-control-sm col-auto" %>
        <div><%= form.label :capacidade %></div>
        <%= form.text_field :capacidade, class:"form-control form-control-sm col-auto" %>
        <div><%= form.label :hr_partida %></div>
        <%= form.text_field :hr_partida, class:"form-control form-control-sm col-auto" %>
        <div><%= form.submit "Adicionar", class: "btn btn-primary mt-2 text-center" %></div>
      <% end %>
      </div>

 <h1></h1>

      <div><h3><%#= @rotums.origem %></h3></div>
      <div><%#= link_to "Show", rotum_path(@rotums.id)  %></div>
    </div>

app/views/rotums/show.html.erb
<%= render "shared/navbar2" %>
<%= render "shared/flashes" %>

<div class="container mt-3">
  <div class="card shadow border-primary" style="--bs-border-opacity: .2;">
    <div class="card-body callout callout-primary">
      <h5 class="card-title mt-3">
        Origem:
        <h2><%= @rotum.origem %></h2>
        Destino
        <h2><%= @rotum.destino %></h2>
      </h5>
      <p class="card-text mt-5">

 <ul class="nav nav-tabs" role="tablist">
      <li class="nav-item">
        <a href="#info" role="tab" data-toggle="tab"
           class="nav-link active"> Viagens </a>
      </li>
      <li class="nav-item">
        <a href="#ratings" role="tab" data-toggle="tab"
           class="nav-link"> Histórico </a>
      </li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" role="tabpanel" id="info">
        <h3> Infos </h3>
        <p> Lorem ipsum sit amet </p>

      <!-- Modal Add Rotum -->

<!-- Button trigger modal -->
<button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
  +
</button>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" data-bs-backdrop="static" data-bs-keyboard="false" aria-hidden="true" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <div class="d-flex justify-content-center bg-white rounded p-5 shadow">
        <%= form_with model: [@rotum,@travel], class:"row g-1 w-10", local: false do |form| %>
        <%= form.select :status,["A iniciar", "Finalizado"], class:"form-control form-control-sm col-auto" %>
        <div><%= form.label :vehicle %></div>
        <%= form.collection_select :vehicle, Vehicle.all, :id, :modelo, prompt: true, class:"form-control mb-3" %>
        <div><%= form.submit "Adicionar", class: "btn btn-primary mt-2 text-center" %></div>
      <% end %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

  <!-- End Modal Add Rotum -->

  <!-- Init Accordion Rotum -->
<% @count = 1 %>
<% @rotum_run.each do |r|  %>
<div class="accordion accordion-flush mt-3" id="accordionFlushExample">
  <div class="accordion-item">
    <h2 class="accordion-header" id="flush-headingOne">
    <% @ind = "#flush-collapseOne" + "#{@count}" %>
    <% @ind2 = "flush-collapseOne" + "#{@count}" %>
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target= <%= @ind %> aria-expanded="false" aria-controls="flush-collapseOne">
        Viagem <%= r.id %> <div class="ml-3 btn btn-warning"><%= r.status %></div>
      </button>
    </h2>

    <div id=<%= @ind2 %> class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
      <% r.vehicles.each do |show| %>
      <div class="accordion-body"> <strong> Modelo: </strong><%= show.modelo %> </div>
      <div class="accordion-body"> <strong> Placa: </strong><%= show.placa %> </div>
      <div class="accordion-body"> <strong> Capacidade: <%= show.capacidade %> </strong> </div>
      <% end %>
      <div><%= link_to "Detalhes", travel_path(r), class: "btn btn-primary ml-3" %></div>
    </div>
  </div>
</div>
</p>
<% @count = @count + 1 %>
<% end %>
</div>


<!-- End Accordion Rotum -->

    <div class="progress" style="height: 3px;">
      <div
        class="progress-bar"
        role="progressbar"
        style="width: 100%;"
        aria-valuenow="25"
        aria-valuemin="0"
        aria-valuemax="100"
      ></div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
     <i class="fa fa-bars btn btn-outline-dark"  type="button" aria-hidden="true" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample"></i>
    <%= link_to "#", class: "navbar-brand" do %>
      <%#= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1>edit user</h1>

app/views/users/new.html.erb
<h1>Novo user</h1>
<div class="d-flex justify-content-center bg-white rounded p-3 shadow">
<%= form_with url: "/users", class:"row g-1 w-10", method: :post do |form| %>
  <div><%= form.label :email %></div>
  <%= form.text_field :email, class:"form-control col-auto" %>
  <div><%= form.label :password %></div>
  <%= form.text_field :password, class:"form-control col-auto" %>
  <div><%= form.label :password_confirmation %></div>
  <%= form.text_field :password_confirmation, class:"form-control col-auto" %>
  <div><%= form.label :role %></div>
  <%= form.select :role,["true","false"], class:"form-control col-auto" %>
  <div><%= form.submit "Salvar", class: "btn btn-primary mt-2 text-center" %></div>
<% end %>
</div>

app/views/vehicles/_form.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="d-flex justify-content-center bg-white rounded p-3 shadow">
      <%= form_with model: @vehicle, class:"row g-1 w-10", local: false do |form| %>
        <%= form.label :modelo %>
        <%= form.text_field :modelo, class:"form-control form-control-sm col-auto" %>
        <div><%= form.label :ano %></div>
        <%= form.text_field :ano, class:"form-control form-control-sm col-auto" %>
        <div><%= form.label :placa %></div>
        <%= form.text_field :placa, class:"form-control form-control-sm col-auto" %>
        <div><%= form.label :capacidade %></div>
        <%= form.text_field :capacidade, class:"form-control form-control-sm col-auto" %>
        <div><%= form.label :status %></div>
        <%= form.select :status,["Liberado", "Em Manutencão", "Defeito"], class:"form-control form-control-sm col-auto" %>
        <div><%= form.label :montadora %></div>
        <%= form.select :montadora,["Pegeout", "Marcopolo", "Fiat", "GM", "Citroen", "Volkswagen"], class:"form-control mb-3" %>
        <div><%= form.submit "Adicionar", class: "btn btn-primary mt-2 text-center" %></div>
      <% end %>
      </div>
    </div>

app/views/vehicles/edit.html.erb
<%= render "form", task: @vehicle %>